name: Badminton Bookings

on:
  schedule:
    - cron: '0 0 * * *' # This runs the script daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4' # Specify the Python version
      
    - name: Install Chrome
      run: |
        # wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version

    - name: Install ChromeDriver
      run: |
        # Fetch the major version of Chrome installed
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+')
          
        # Get the latest ChromeDriver version for the Chrome major version
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          
        # Fall back to the latest ChromeDriver version if specific version not found
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
            CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        fi
          
        wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        sudo apt-get install -y unzip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        DISPLAY: ':99' # Set display environment variable for headless mode
      run: |
        # Start Xvfb (X virtual framebuffer) for headless mode
        Xvfb :99 -ac &
        python booking.py # Replace 'your_script.py' with your file name
