name: Badminton Bookings

on:
  schedule:
    - cron: '0 0 * * *' # This runs the script daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4' # Specify the Python version
      
      # Chrome    
      - wget -q -O chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.122/linux64/chrome-linux64.zip   
      - unzip chrome-linux64.zip    
      - rm chrome-linux64.zip    
      - mv chrome-linux64 /opt/chrome/    
      - ln -s /opt/chrome/chrome /usr/local/bin/   
      # Chromedriver   
      - wget -q -O chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.122/linux64/chromedriver-linux64.zip   
      - unzip -j chromedriver-linux64.zip chromedriver-linux64/chromedriver  
      - rm chromedriver-linux64.zip    
      - mv chromedriver /usr/local/bin/   
      - chrome --version   
      - chromedriver --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python booking.py
